[0m17:08:38.917998 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019000FF5630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019003D7F580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019003D7F370>]}


============================== 17:08:38.921184 | 938659d9-38bb-4f2f-86b3-be31b848180a ==============================
[0m17:08:38.921184 [info ] [MainThread]: Running with dbt=1.7.7
[0m17:08:38.921184 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Vijay\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init dbtlearn', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:08:38.921184 [debug] [MainThread]: Starter project path: J:\5. Training\36. dbt\my-dbt\dbt\venv\lib\site-packages\dbt\include\starter_project
[0m17:08:39.001804 [info ] [MainThread]: 
Your new dbt project "dbtlearn" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:08:39.003808 [info ] [MainThread]: Setting up your profile.
[0m09:28:23.166696 [error] [MainThread]: Encountered an error:

[0m09:28:23.235052 [error] [MainThread]: Traceback (most recent call last):
  File "J:\5. Training\36. dbt\my-dbt\dbt\venv\lib\site-packages\dbt\cli\requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
  File "J:\5. Training\36. dbt\my-dbt\dbt\venv\lib\site-packages\dbt\cli\requires.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "J:\5. Training\36. dbt\my-dbt\dbt\venv\lib\site-packages\dbt\cli\main.py", line 515, in init
    results = task.run()
  File "J:\5. Training\36. dbt\my-dbt\dbt\venv\lib\site-packages\dbt\task\init.py", line 344, in run
    self.setup_profile(profile_name)
  File "J:\5. Training\36. dbt\my-dbt\dbt\venv\lib\site-packages\dbt\task\init.py", line 264, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "J:\5. Training\36. dbt\my-dbt\dbt\venv\lib\site-packages\dbt\task\init.py", line 181, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "J:\5. Training\36. dbt\my-dbt\dbt\venv\lib\site-packages\dbt\task\init.py", line 165, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "J:\5. Training\36. dbt\my-dbt\dbt\venv\lib\site-packages\dbt\task\init.py", line 131, in generate_target_from_input
    target[key] = click.prompt(
  File "J:\5. Training\36. dbt\my-dbt\dbt\venv\lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "J:\5. Training\36. dbt\my-dbt\dbt\venv\lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m09:28:23.241050 [debug] [MainThread]: Command `dbt init` failed at 09:28:23.241050 after 58784.47 seconds
[0m09:28:23.243055 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019000FF5630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001900445B430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001900445B4C0>]}
[0m09:28:23.244053 [debug] [MainThread]: Flushing usage events
[0m09:32:04.976991 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190D49D5C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190D775F520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190D775F310>]}


============================== 09:32:04.981992 | af0bcbab-2a5b-43f2-9854-354e558015a1 ==============================
[0m09:32:04.981992 [info ] [MainThread]: Running with dbt=1.7.7
[0m09:32:04.983998 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Vijay\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init dbtlearn', 'send_anonymous_usage_stats': 'True'}
[0m09:32:04.984994 [info ] [MainThread]: A project called dbtlearn already exists here.
[0m09:32:04.986994 [debug] [MainThread]: Command `dbt init` succeeded at 09:32:04.986994 after 0.16 seconds
[0m09:32:04.987992 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190D49D5C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190D775F2E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190D775F5B0>]}
[0m09:32:04.989008 [debug] [MainThread]: Flushing usage events
[0m15:15:36.906460 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DD35BA9060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DD388EF790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DD388ED840>]}


============================== 15:15:36.912460 | 35605902-2a49-4ed4-a540-097e58aae7d3 ==============================
[0m15:15:36.912460 [info ] [MainThread]: Running with dbt=1.7.7
[0m15:15:36.915472 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Vijay\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt seed', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:15:36.918468 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path J:\5. Training\36. dbt\my-dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:15:36.924826 [debug] [MainThread]: Command `dbt seed` failed at 15:15:36.923826 after 0.16 seconds
[0m15:15:36.926831 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DD35BA9060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DD388EC460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DD388EFBE0>]}
[0m15:15:36.928831 [debug] [MainThread]: Flushing usage events
[0m15:15:55.952632 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D170E9B250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D173BDB790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D173BDBF70>]}


============================== 15:15:55.958631 | 1c521dde-a347-46a4-b819-7303d6e07416 ==============================
[0m15:15:55.958631 [info ] [MainThread]: Running with dbt=1.7.7
[0m15:15:55.959646 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Vijay\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt seed --profiles-dir C:\\Users\\Vijay\\.dbt', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:15:55.960634 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path J:\5. Training\36. dbt\my-dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:15:55.963637 [debug] [MainThread]: Command `dbt seed` failed at 15:15:55.963637 after 0.19 seconds
[0m15:15:55.964631 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D170E9B250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D173BD84F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D173BDBBE0>]}
[0m15:15:55.965631 [debug] [MainThread]: Flushing usage events
[0m17:24:58.509913 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D164A2B250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D167769FF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D16776B730>]}


============================== 17:24:58.524340 | 4facff8f-5b63-446b-8a17-fe92e421332d ==============================
[0m17:24:58.524340 [info ] [MainThread]: Running with dbt=1.7.7
[0m17:24:58.525936 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Vijay\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt docs generate', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:24:58.526985 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path J:\5. Training\36. dbt\my-dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:24:58.530167 [debug] [MainThread]: Command `dbt docs generate` failed at 17:24:58.529644 after 0.16 seconds
[0m17:24:58.530692 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D164A2B250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D16776AAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D167768CD0>]}
[0m17:24:58.531753 [debug] [MainThread]: Flushing usage events
